# docker network create proxy
# docker compose up -d --build --force-recreate

services:
  traefik:
    image: traefik:v2.9
    container_name: careplus_traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.network=proxy'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--api.dashboard=false' # Specifically disables the dashboard
      - '--api.insecure=false' # Disables the insecure API endpoint
    ports:
      - '80:80'
      - '8080:8080' # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - proxy

  redis:
    image: redis:7-alpine
    container_name: careplus_redis
    ports:
      - '6379:6379'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.redis.service=redis'
      - 'traefik.http.services.redis.loadbalancer.server.port=6379'
    networks:
      - proxy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: careplus_rabbitmq
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # Management UI
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.rabbitmq.service=rabbitmq'
      - 'traefik.http.services.rabbitmq.loadbalancer.server.port=15672'
      - 'traefik.http.services.rabbitmq.loadbalancer.server.port=5672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s # Check more frequently at start
      timeout: 5s
      retries: 10 # Give it enough time to boot
      start_period: 10s # Wait 10s before starting checks to save CPU
    networks:
      - proxy

  frontend:
    image: 'shinsouhitoshi1203/careplus_frontend:latest'
    container_name: careplus_frontend
    # env_file:
    #   - .env.docker
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.frontend.rule=Host(`web.ayatollah.site`)'
      - 'traefik.http.routers.frontend.entrypoints=web'
      - 'traefik.http.routers.frontend.service=frontend'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'
    networks:
      - default
      - proxy

  backend:
    container_name: careplus_backend
    image: 'shinsouhitoshi1203/careplus_backend:latest'
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.backend.rule=Host(`be.ayatollah.site`)'
      - 'traefik.http.routers.backend.entrypoints=web'
      - 'traefik.http.routers.backend.service=backend'
      - 'traefik.http.services.backend.loadbalancer.server.port=8080'
    networks:
      - default
      - proxy

networks:
  proxy:
    name: proxy
    external: true
